apiVersion: v1
kind: Service
metadata:
  name: {{ include "blitz-gateway.fullname" . }}
  labels:
    {{- include "blitz-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    {{- include "blitz-gateway.selectorLabels" . | nindent 4 }}
